### ISSUE TITLE
Readme example not working

### ISSUE THREAD

**Issue by arjunmenon** [cyberarm/cyberarm_engine#14]
Hey, checked on windows and wsl. I get this error
```
(irb):8:in `block in setup': undefined method `label' for an instance of Hello (NoMethodError)
        from /.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/cyberarm_engine-0.24.4/lib/cyberarm_engine/ui/elements/container.rb:37:in `build'
        from /.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/cyberarm_engine-0.24.4/lib/cyberarm_engine/ui/dsl.rb:134:in `container'
        from /.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/cyberarm_engine-0.24.4/lib/cyberarm_engine/ui/dsl.rb:8:in `stack'
        from (irb):7:in `setup'
        from /.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/cyberarm_engine-0.24.4/lib/cyberarm_engine/window.rb:155:in `push_state'
        from (irb):21:in `setup'
        from /.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/cyberarm_engine-0.24.4/lib/cyberarm_engine/window.rb:49:in `initialize'
```

**Comment by cyberarm** [comment]
Oh bother, I didn't update the README when I axed the `label` method. Should be replaced with `para`
